### ISSUE TITLE
How to reduce size of data generation?

### ISSUE THREAD

**Issue by AnnabellaMacaluso** [Boey-li/AdaptiGraph#5]
Hi, using the default configurations, the data generated consumes terabytes of storage. The data provided is not nearly as large, what method was used to reduce the size of sim_data generated?

**Comment by Boey-li** [comment]
Hello, the images take up a significant amount of storage space, but they are only utilized for qualitative visualization during rollouts and are not involved in the training process. To reduce the size of the simulation data, you can skip saving the images used for training.

**Comment by AnnabellaMacaluso** [comment]
Sounds good, thanks!
