### ISSUE TITLE
Planning and inferencing on the pyFlex simulation environment

### ISSUE THREAD

**Issue by AlanYoung123** [Boey-li/AdaptiGraph#6]
Thank you for maintaining this open-source project; it’s been very helpful! I have 2 questions: 1. Can I inference the physical properties of unseen objects and carry out manipulation tasks on the pyFlex simulation environment?  2. Do you provide code about this? Looking forward to your reply!

**Comment by Boey-li** [comment]
Hello, thanks for the questions. 

Yes, you can. But we do not conduct planning experiments in simulation and thus we do not have the related code. You can refer to [Dyn-Res](https://github.com/WangYixuan12/dyn-res-pile-manip), which includes the [planning code](https://github.com/WangYixuan12/dyn-res-pile-manip/blob/main/visualize_mpc.py) in PyFleX simulation environment.

**Comment by AlanYoung123** [comment]
Thanks so much for you reply!
